[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "math_utils"
version = "0.1"
dependencies = ["numpy"]

[tool.hatch.build.targets.wheel]
packages = ["math_utils"]