name: Python tests

on: [push, pull_request]  # 触发条件：当你 push 或发起 PR 时自动运行

jobs:
  build:
    runs-on: ubuntu-latest  # 在 GitHub 提供的 Ubuntu 环境中运行

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 你可以改成你项目中用的版本，例如 '3.10' 或 '3.11'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest

      - name: Run tests
        run: |
          pytest tests
